<a href="https://colab.research.google.com/github/wildenali/TensorFlow_Basic/blob/master/002_tensorBasic/a-basicTensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
# Rank 0
# Default Name
r1 = tf.constant(1, tf.int16)
print(r1)

tf.Tensor(1, shape=(), dtype=int16)


In [ ]:
# Named my_scalar
r2 = tf.constant(1, tf.int16, name="my_scalar")
print(r2)

tf.Tensor(1, shape=(), dtype=int16)


In [ ]:
# Decimal
r1_decimal = tf.constant(1.1233, tf.float32)
print(r1_decimal)

tf.Tensor(1.1233, shape=(), dtype=float32)


In [ ]:
# Decimal
r1_string = tf.constant("ini siapa", tf.string)
print(r1_string)

tf.Tensor(b'ini siapa', shape=(), dtype=string)


In [ ]:
# Rank 1
r1_vector = tf.constant([1,3,5], tf.int16)
print(r1_vector)

r2_boolean = tf.constant([True, True, False], tf.bool)
print(r2_boolean)

tf.Tensor([1 3 5], shape=(3,), dtype=int16)
tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [ ]:
# Rank 2
r2_matrix = tf.constant([[1, 5],
                         [3, 4]], tf.int16)
print(r2_matrix)

tf.Tensor(
[[1 5]
 [3 4]], shape=(2, 2), dtype=int16)


In [ ]:
# Rank 3
r3_matrix = tf.constant([[1, 5],
                         [3, 4],
                         [5, 6]], tf.int16)
print(r3_matrix)

tf.Tensor(
[[1 5]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int16)


In [ ]:
# Shape of tensor
m_shape = tf.constant([[11, 15],
                       [31, 41],
                       [52, 63]])
print(m_shape)
print("---")
m_shape.shape
print(tf.__version__)

tf.Tensor(
[[11 15]
 [31 41]
 [52 63]], shape=(3, 2), dtype=int32)
---
2.7.0


In [ ]:
# Create a vector of 0
print(tf.zeros(10))

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)


In [ ]:
# Create a vector of 1
print(tf.ones([10, 10]))
print(tf.ones(m_shape.shape[0]))
print(tf.ones(m_shape.shape[1]))
print(tf.ones(m_shape.shape))

tf.Tensor(
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]], shape=(10, 10), dtype=float32)
tf.Tensor([1. 1. 1.], shape=(3,), dtype=float32)
tf.Tensor([1. 1.], shape=(2,), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [ ]:
# Type of data
print(m_shape.dtype)

<dtype: 'int32'>


In [ ]:
# Change type of data
type_float = tf.constant(3.123456789, tf.float32)
type_int = tf.cast(type_float, dtype=tf.int32)
print(type_float.dtype)
print(type_int.dtype)

<dtype: 'float32'>
<dtype: 'int32'>
